export const CATEGORIES = [
  { id: '1', name: 'Food & Dining', icon: '🍔', color: 'bg-orange-100' },
  { id: '2', name: 'Transportation', icon: '🚗', color: 'bg-blue-100' },
  { id: '3', name: 'Entertainment', icon: '🎬', color: 'bg-purple-100' },
  { id: '4', name: 'Utilities', icon: '💡', color: 'bg-yellow-100' },
  { id: '5', name: 'Healthcare', icon: '🏥', color: 'bg-red-100' },
  { id: '6', name: 'Shopping', icon: '🛍️', color: 'bg-green-100' },
  { id: '7', name: 'Travel', icon: '✈️', color: 'bg-indigo-100' },
  { id: '8', name: 'Education', icon: '📚', color: 'bg-teal-100' },
  { id: '9', name: 'Personal Care', icon: '💇‍♀️', color: 'bg-pink-100'},
  { id: '10', name: 'Other', icon: '📦', color: 'bg-gray-100' },
  { id: '11', name: 'Income', icon: '💰', color: 'bg-green-200'},
  { id: '12', name: 'Savings', icon: '🏦', color: 'bg-blue-200' },
  { id: '13', name: 'Investments', icon: '📈', color: 'bg-yellow-200' },
  { id: '14', name: 'Gifts & Donations', icon: '🎁', color: 'bg-purple-200' },
  { id: '15', name: 'Subscriptions', icon: '📺', color: 'bg-pink-200' },
  { id: '16', name: 'Miscellaneous', icon: '🔧', color: 'bg-gray-200' },
  { id: '17', name: 'Data & Airtime', icon: '📶', color: 'bg-cyan-100' },
  { id: '18', name: 'Digital & AI', icon: '🤖', color: 'bg-violet-200' },
];